version: "3.7"
services:
  app:
    image: kooldev/php:8.0-nginx
    ports:
    - ${KOOL_APP_PORT:-80}:80
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
    - kool_global
  database:
    image: mysql:8
    ports:
    - ${KOOL_DATABASE_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel_vuejs_test'
      MYSQL_USER: 'root'
      MYSQL_PASS: ''
    volumes:
    - database:/var/lib/mysql:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
  cache:
    image: redis:6-alpine
    volumes:
    - cache:/data:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
volumes:
  database: null
  cache: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
